// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Device struct {
	ID          string `json:"id"`
	Name        string `json:"name"`
	DeviceBrand string `json:"DeviceBrand"`
	CreatedAt   string `json:"CreatedAt"`
}

type Mutation struct {
}

type NewDevice struct {
	Name        string `json:"name"`
	DeviceBrand string `json:"deviceBrand"`
}

type Query struct {
}
